Unit test for Issue 70
klarna/HiveRunner pull request #144
Opened 2021-03-09 15:35 UTC by shermosa

Adding unit test to check that issue https://github.com/klarna/HiveRunner/issues/70 doesn't happen anymore.

2021-03-09 16:02 UTC, massdosage requested changes

2021-03-09 16:02 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/AggregateViewTest.java
> +@RunWith(StandaloneHiveRunner.class)
Going forward I think all new tests should use JUnit5 and the extension instead of the Runner, can you make it so here please?

2021-03-09 16:02 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/AggregateViewTest.java
> +
Remove blank line plz

2021-03-09 16:02 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/AggregateViewTest.java
> +
Remove blank line plz

2021-03-09 16:02 UTC, massdosage commented on src/test/resources/AggregateViewTest/create_table.sql
> +
GitHub is moaning about this file not having a closing line break (you can see it in the diff view in the web UI). Perhaps it has some Mac line break or other blank character but not a standard *nix one? I don't know as there appears to be one here but GH doesn't like it.

2021-03-09 16:43 UTC, massdosage requested changes

2021-03-09 16:43 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/AggregateViewTest.java
> +   * This bug is solved when upgrading HiveRunner to any version above 3.2.1 (at least 4.0.0).
```suggestion
   * This bug is solved when upgrading HiveRunner to version 4.0.0 or above (most likely due to move from Hive 1.x to 2.x).
```

2021-03-09 16:43 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/AggregateViewTest.java
> +
Remove the blank line so the javadoc is associated with the method.

2021-03-09 17:20 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/AggregateViewTest.java
> +  protected HiveShell shell;
```suggestion
  private HiveShell shell;
```

2021-03-19 12:07 UTC, massdosage approved these changes

2021-03-19 12:10 UTC, massdosage commented
Fixes #70

2021-03-19 12:17 UTC, JayGreeeen approved these changes

2021-03-19 12:37 UTC, merged