Updating test classes to newer dependencies of Mockito and JUnit
klarna/HiveRunner pull request #151
Opened 2021-03-16 11:55 UTC by shermosa

PR for this HR issue https://github.com/klarna/HiveRunner/issues/145

2021-03-16 14:11 UTC, massdosage requested changes

2021-03-16 14:11 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/TimeoutAndRetryTest.java
> +}
Add a [closing line break](https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file) to EOF please.

2021-03-16 14:11 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/builder/HiveShellBaseTest.java
> +  @Rule
Can you put the indentations here back to how they were? Otherwise it's hard to spot what actually changed.

2021-03-16 14:11 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/examples/HelloHiveRunnerParamaterized.java
This test needs to be renamed to `HelloHiveRunnerParamaterizedTest` (it's quite likely it's not currently being run...)

2021-03-16 14:11 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/examples/junit4/HelloHiveRunnerTest.java
> +import static org.junit.jupiter.api.Assertions.assertArrayEquals;
This is in the Junit4 package so shouldn't be updated to Junit5.

2021-03-16 14:34 UTC, shermosa commented on src/test/java/com/klarna/hiverunner/OrcSnappyTest.java
> +    @Disabled // Fails with java.lang.UnsatisfiedLinkError: org.apache.hadoop.util.NativeCodeLoader.buildSupportsSnappy()Z
Yes, they both fail

2021-03-16 15:50 UTC, JayGreeeen commented on src/test/java/com/klarna/hiverunner/HiveRunnerExtensionTest.java
> +
```suggestion
```

2021-03-16 15:54 UTC, JayGreeeen commented on src/test/java/com/klarna/hiverunner/config/HiveRunnerConfigTest.java
>  }
Needs line at EOF

2021-03-17 15:46 UTC, massdosage requested changes

2021-03-17 15:46 UTC, massdosage commented on pom.xml
> +      <version>3.8.0</version>
Can you make this a property? `mockito.version` and then use it for both this and the next dependency as I think they're released together so we want to keep using the same version for both.

2021-03-17 15:46 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/HiveServerContainerTest.java
> +        Assertions.assertThrows(IllegalArgumentException.class, () -> container.executeStatement("use foo"));
Mmmm, this isn't testing quite the same thing. We need to call `getCause` on the `IllegalArgumentException` and assert that it's a `HiveSQLException`.

2021-03-17 15:46 UTC, massdosage commented on src/test/java/com/klarna/hiverunner/OrcSnappyTest.java
> +    @Disabled // Fails with java.lang.UnsatisfiedLinkError: org.apache.hadoop.util.NativeCodeLoader.buildSupportsSnappy()Z
OK, thanks for checking.

2021-03-18 09:03 UTC, massdosage approved these changes

2021-03-18 09:09 UTC, JayGreeeen approved these changes

2021-03-18 09:15 UTC, merged

2021-03-18 09:17 UTC, massdosage commented
Fixes #145